language: python

python:
 - "3.4"

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y python-numpy

env:
 - DJANGO_VERSION=1.8.2

install:
 - pip install -q Django==$DJANGO_VERSION
 - pip install coverage

script:
 - coverage python manage.py test
 - pip install pillow

script:
 - python manage.py test

after_success:
 - coverage report
